<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_write a review_img-circle</name>
   <tag></tag>
   <elementGuidId>b11edc98-33b7-4083-9fb4-3b2c6b7c974f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='mac']/body/div[2]/div/section/div[3]/div[5]/div/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>admin/view/default/image/icons/categories_icon.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Categories</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mac&quot;)/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;wrapper_c page_width&quot;]/section[1]/div[@class=&quot;mainpanel&quot;]/div[@class=&quot;contentpanel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 col-sm-3 col-md-2 shortcut temp text-center&quot;]/a[1]/img[@class=&quot;img-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='mac']/body/div[2]/div/section/div[3]/div[5]/div/div/div/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Categories']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
